<?php

namespace Anon\Core\Database\Migration;

use Anon\Core\Database\Connection;
use Anon\Core\Database\Mongo\Connection as MongoConnection;
use Anon\Core\Facade\DB;
use Anon\Core\Foundation\App;
use PDO;

class Migrator
{
    protected string $table = 'migrations';
    protected string $path;

    public function __construct()
    {
        $this->path = APP_PATH . DIRECTORY_SEPARATOR . 'database' . DIRECTORY_SEPARATOR . 'migrations';
        if (!is_dir($this->path)) {
            mkdir($this->path, 0755, true);
        }
    }

    /**
     * 确保存储迁移记录的表存在
     */
    protected function ensureTableExists(): void
    {
        $connection = $this->getConnection();

        if ($connection instanceof MongoConnection) {
            DB::schema()->create($this->table);
            return;
        }

        $driver = DB::getPdo()->getAttribute(PDO::ATTR_DRIVER_NAME);
        $sql = $this->buildMigrationTableSql($driver);
        DB::statement($sql);
    }

    protected function buildMigrationTableSql(string $driver): string
    {
        return match (strtolower($driver)) {
            'sqlite' => "CREATE TABLE IF NOT EXISTS {$this->table} (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                migration VARCHAR(255) NOT NULL,
                batch INTEGER NOT NULL
            )",
            'pgsql' => "CREATE TABLE IF NOT EXISTS {$this->table} (
                id BIGSERIAL PRIMARY KEY,
                migration VARCHAR(255) NOT NULL,
                batch INTEGER NOT NULL
            )",
            'sqlsrv' => "IF OBJECT_ID(N'{$this->table}', N'U') IS NULL
                CREATE TABLE {$this->table} (
                    id INT IDENTITY(1,1) PRIMARY KEY,
                    migration NVARCHAR(255) NOT NULL,
                    batch INT NOT NULL
                )",
            'oci', 'oracle' => "BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE {$this->table} (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    migration VARCHAR2(255) NOT NULL,
                    batch NUMBER(10) NOT NULL
                )';
            EXCEPTION
                WHEN OTHERS THEN
                    IF SQLCODE != -955 THEN
                        RAISE;
                    END IF;
            END;",
            default => "CREATE TABLE IF NOT EXISTS {$this->table} (
                id INT AUTO_INCREMENT PRIMARY KEY,
                migration VARCHAR(255) NOT NULL,
                batch INT NOT NULL
            )",
        };
    }

    /**
     * 获取所有已执行的迁移
     */
    protected function getRanMigrations(): array
    {
        $this->ensureTableExists();
        if ($this->isMongoConnection()) {
            $rows = DB::table($this->table)
                ->orderBy('batch')
                ->orderBy('migration')
                ->get();

            return array_column($rows, 'migration');
        }

        $rows = DB::select("SELECT migration FROM {$this->table} ORDER BY batch ASC, migration ASC");
        return array_column($rows, 'migration');
    }

    /**
     * 获取下一个批次号
     */
    protected function getNextBatchNumber(): int
    {
        $this->ensureTableExists();
        if ($this->isMongoConnection()) {
            return (int) (DB::table($this->table)->max('batch') ?? 0) + 1;
        }

        $rows = DB::select("SELECT MAX(batch) as batch FROM {$this->table}");
        return (int)($rows[0]['batch'] ?? 0) + 1;
    }

    /**
     * 执行所有未运行的迁移
     */
    public function run(): array
    {
        $ran = $this->getRanMigrations();
        $files = glob($this->path . DIRECTORY_SEPARATOR . '*.php');
        if (!$files) {
            return [];
        }

        $pending = [];
        foreach ($files as $file) {
            $name = basename($file, '.php');
            if (!in_array($name, $ran)) {
                $pending[] = $file;
            }
        }

        if (empty($pending)) {
            return [];
        }

        $batch = $this->getNextBatchNumber();
        $executed = [];

        foreach ($pending as $file) {
            require_once $file;
            $name = basename($file, '.php');
            // 约定类名为去除了时间前缀的文件名，例如 20260510_123456_CreateUsersTable -> CreateUsersTable
            $parts = explode('_', $name);
            $className = $parts[count($parts) - 1];

            if (class_exists($className)) {
                /** @var Migration $migration */
                $migration = new $className();
                $migration->up();

                $this->recordMigration($name, $batch);
                $executed[] = $name;
            }
        }

        return $executed;
    }

    protected function recordMigration(string $name, int $batch): void
    {
        if ($this->isMongoConnection()) {
            DB::table($this->table)->insert([
                'migration' => $name,
                'batch' => $batch,
            ]);

            return;
        }

        DB::statement("INSERT INTO {$this->table} (migration, batch) VALUES (?, ?)", [$name, $batch]);
    }

    protected function isMongoConnection(): bool
    {
        return $this->getConnection() instanceof MongoConnection;
    }

    protected function getConnection(): Connection
    {
        /** @var Connection $connection */
        $connection = App::getInstance()->make('db');

        return $connection;
    }
}
